spring.application.name=picpaysimplificado

# Configurações do Banco H2 (Corrigido: Sem comentário e com DB_CLOSE_DELAY ativo)
spring.datasource.url=jdbc:h2:mem:picpaydb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Ativa o console do H2 no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuração corrigida para forçar a execução do import.sql
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# URLs dos Serviços Externos (Mocks do Desafio)
app.services.authorization.url=https://util.devi.tools/api/v2/authorize
app.services.notification.url=https://util.devi.tools/api/v1/notify

# Garante o sincronismo da carga de dados com a criação do schema
spring.jpa.defer-datasource-initialization=true
